/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export interface ChatMessage {
  'id' : bigint,
  'file' : [] | [FileRef],
  'isSystem' : boolean,
  'text' : string,
  'timestamp' : bigint,
  'senderName' : string,
}
export type ClassroomDuration = { 'min30' : null } |
  { 'hour1' : null } |
  { 'hour1half' : null };
export type ClassroomId = bigint;
export interface ClassroomView {
  'id' : ClassroomId,
  'title' : string,
  'onlineCount' : bigint,
  'duration' : ClassroomDuration,
  'createdAt' : Timestamp,
  'roomCode' : string,
}
export type Email = string;
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface FileRef {
  'url' : string,
  'name' : string,
  'size' : bigint,
  'mimeType' : string,
}
export type LoginResult = { 'ok' : Session } |
  { 'invalidCredentials' : null };
export type Password = string;
export interface ReactionEvent {
  'id' : bigint,
  'timestamp' : bigint,
  'senderName' : string,
  'symbol' : string,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type Role = { 'teacher' : null } |
  { 'student' : null };
export interface Session {
  'token' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : Role,
  'email' : Email,
}
export interface SpotlightState { 'active' : boolean, 'studentName' : string }
export interface StickerState { 'studentName' : string, 'symbol' : string }
export interface TimerState {
  'startTime' : bigint,
  'durationSec' : bigint,
  'running' : boolean,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface WhiteboardAction {
  'id' : bigint,
  'kind' : string,
  'color' : string,
  'timestamp' : bigint,
  'senderName' : string,
  'width' : number,
  'points' : Array<number>,
}
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'broadcastWhiteboardAction' : ActorMethod<
    [string, Array<number>, string, number],
    undefined
  >,
  'createClassroom' : ActorMethod<[string, ClassroomDuration], ClassroomView>,
  'deleteClassroom' : ActorMethod<[ClassroomId], boolean>,
  'endSession' : ActorMethod<[string], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentSession' : ActorMethod<[string], [] | [Session]>,
  'getOnline' : ActorMethod<[string], Array<Principal>>,
  'getRoomLink' : ActorMethod<[ClassroomId], [] | [string]>,
  'getSessionEnded' : ActorMethod<[string], boolean>,
  'getSpotlight' : ActorMethod<[], SpotlightState>,
  'getSticker' : ActorMethod<[], StickerState>,
  'getTimer' : ActorMethod<[], TimerState>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinRoom' : ActorMethod<[string], undefined>,
  'leaveRoom' : ActorMethod<[string], undefined>,
  'listChatMessages' : ActorMethod<[], Array<ChatMessage>>,
  'listClassrooms' : ActorMethod<[], Array<ClassroomView>>,
  'listReactions' : ActorMethod<[], Array<ReactionEvent>>,
  'listWhiteboardActions' : ActorMethod<[], Array<WhiteboardAction>>,
  'login' : ActorMethod<[Email, Password], LoginResult>,
  'logout' : ActorMethod<[string], undefined>,
  'schema' : ActorMethod<[], string>,
  'searchClassrooms' : ActorMethod<
    [string, [] | [Timestamp]],
    Array<ClassroomView>
  >,
  'sendChatMessage' : ActorMethod<[string, [] | [FileRef]], bigint>,
  'sendReaction' : ActorMethod<[string], bigint>,
  'setSpotlight' : ActorMethod<[string], undefined>,
  'setSticker' : ActorMethod<[string, string], undefined>,
  'setTimer' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];