/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ClassroomDuration = IDL.Variant({
  'min30' : IDL.Null,
  'hour1' : IDL.Null,
  'hour1half' : IDL.Null,
});
export const ClassroomId = IDL.Nat;
export const Timestamp = IDL.Int;
export const ClassroomView = IDL.Record({
  'id' : ClassroomId,
  'title' : IDL.Text,
  'onlineCount' : IDL.Nat,
  'duration' : ClassroomDuration,
  'createdAt' : Timestamp,
  'roomCode' : IDL.Text,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const SpotlightState = IDL.Record({
  'active' : IDL.Bool,
  'studentName' : IDL.Text,
});
export const StickerState = IDL.Record({
  'studentName' : IDL.Text,
  'symbol' : IDL.Text,
});
export const TimerState = IDL.Record({
  'startTime' : IDL.Int,
  'durationSec' : IDL.Nat,
  'running' : IDL.Bool,
});
export const FileRef = IDL.Record({
  'url' : IDL.Text,
  'name' : IDL.Text,
  'size' : IDL.Nat,
  'mimeType' : IDL.Text,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'file' : IDL.Opt(FileRef),
  'isSystem' : IDL.Bool,
  'text' : IDL.Text,
  'timestamp' : IDL.Int,
  'senderName' : IDL.Text,
});
export const ReactionEvent = IDL.Record({
  'id' : IDL.Nat,
  'timestamp' : IDL.Int,
  'senderName' : IDL.Text,
  'symbol' : IDL.Text,
});
export const WhiteboardAction = IDL.Record({
  'id' : IDL.Nat,
  'kind' : IDL.Text,
  'color' : IDL.Text,
  'timestamp' : IDL.Int,
  'senderName' : IDL.Text,
  'width' : IDL.Float64,
  'points' : IDL.Vec(IDL.Float64),
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'broadcastWhiteboardAction' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Float64), IDL.Text, IDL.Float64],
      [],
      [],
    ),
  'createClassroom' : IDL.Func(
      [IDL.Text, ClassroomDuration],
      [ClassroomView],
      [],
    ),
  'deleteClassroom' : IDL.Func([ClassroomId], [IDL.Bool], []),
  'endSession' : IDL.Func([IDL.Text], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOnline' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Principal)], ['query']),
  'getRoomLink' : IDL.Func([ClassroomId], [IDL.Opt(IDL.Text)], ['query']),
  'getSessionEnded' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'getSpotlight' : IDL.Func([], [SpotlightState], ['query']),
  'getSticker' : IDL.Func([], [StickerState], ['query']),
  'getTimer' : IDL.Func([], [TimerState], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinRoom' : IDL.Func([IDL.Text], [], []),
  'leaveRoom' : IDL.Func([IDL.Text], [], []),
  'listChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'listClassrooms' : IDL.Func([], [IDL.Vec(ClassroomView)], ['query']),
  'listReactions' : IDL.Func([], [IDL.Vec(ReactionEvent)], ['query']),
  'listWhiteboardActions' : IDL.Func(
      [],
      [IDL.Vec(WhiteboardAction)],
      ['query'],
    ),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchClassrooms' : IDL.Func(
      [IDL.Text, IDL.Opt(Timestamp)],
      [IDL.Vec(ClassroomView)],
      ['query'],
    ),
  'sendChatMessage' : IDL.Func([IDL.Text, IDL.Opt(FileRef)], [IDL.Nat], []),
  'sendReaction' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'setSpotlight' : IDL.Func([IDL.Text], [], []),
  'setSticker' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setTimer' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ClassroomDuration = IDL.Variant({
    'min30' : IDL.Null,
    'hour1' : IDL.Null,
    'hour1half' : IDL.Null,
  });
  const ClassroomId = IDL.Nat;
  const Timestamp = IDL.Int;
  const ClassroomView = IDL.Record({
    'id' : ClassroomId,
    'title' : IDL.Text,
    'onlineCount' : IDL.Nat,
    'duration' : ClassroomDuration,
    'createdAt' : Timestamp,
    'roomCode' : IDL.Text,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const SpotlightState = IDL.Record({
    'active' : IDL.Bool,
    'studentName' : IDL.Text,
  });
  const StickerState = IDL.Record({
    'studentName' : IDL.Text,
    'symbol' : IDL.Text,
  });
  const TimerState = IDL.Record({
    'startTime' : IDL.Int,
    'durationSec' : IDL.Nat,
    'running' : IDL.Bool,
  });
  const FileRef = IDL.Record({
    'url' : IDL.Text,
    'name' : IDL.Text,
    'size' : IDL.Nat,
    'mimeType' : IDL.Text,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'file' : IDL.Opt(FileRef),
    'isSystem' : IDL.Bool,
    'text' : IDL.Text,
    'timestamp' : IDL.Int,
    'senderName' : IDL.Text,
  });
  const ReactionEvent = IDL.Record({
    'id' : IDL.Nat,
    'timestamp' : IDL.Int,
    'senderName' : IDL.Text,
    'symbol' : IDL.Text,
  });
  const WhiteboardAction = IDL.Record({
    'id' : IDL.Nat,
    'kind' : IDL.Text,
    'color' : IDL.Text,
    'timestamp' : IDL.Int,
    'senderName' : IDL.Text,
    'width' : IDL.Float64,
    'points' : IDL.Vec(IDL.Float64),
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'broadcastWhiteboardAction' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Float64), IDL.Text, IDL.Float64],
        [],
        [],
      ),
    'createClassroom' : IDL.Func(
        [IDL.Text, ClassroomDuration],
        [ClassroomView],
        [],
      ),
    'deleteClassroom' : IDL.Func([ClassroomId], [IDL.Bool], []),
    'endSession' : IDL.Func([IDL.Text], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOnline' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Principal)], ['query']),
    'getRoomLink' : IDL.Func([ClassroomId], [IDL.Opt(IDL.Text)], ['query']),
    'getSessionEnded' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'getSpotlight' : IDL.Func([], [SpotlightState], ['query']),
    'getSticker' : IDL.Func([], [StickerState], ['query']),
    'getTimer' : IDL.Func([], [TimerState], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinRoom' : IDL.Func([IDL.Text], [], []),
    'leaveRoom' : IDL.Func([IDL.Text], [], []),
    'listChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'listClassrooms' : IDL.Func([], [IDL.Vec(ClassroomView)], ['query']),
    'listReactions' : IDL.Func([], [IDL.Vec(ReactionEvent)], ['query']),
    'listWhiteboardActions' : IDL.Func(
        [],
        [IDL.Vec(WhiteboardAction)],
        ['query'],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchClassrooms' : IDL.Func(
        [IDL.Text, IDL.Opt(Timestamp)],
        [IDL.Vec(ClassroomView)],
        ['query'],
      ),
    'sendChatMessage' : IDL.Func([IDL.Text, IDL.Opt(FileRef)], [IDL.Nat], []),
    'sendReaction' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'setSpotlight' : IDL.Func([IDL.Text], [], []),
    'setSticker' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setTimer' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };